# Generated by Django 5.1.6 on 2025-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('Romantic', 'Romantic'), ('Solo', 'Solo'), ('Family', 'Family'), ('Friends', 'Friends'), ('Business Trip', 'Business Trip'), ('Honeymoon', 'Honeymoon'), ('Adventure', 'Adventure')], max_length=50)),
                ('budget', models.PositiveIntegerField()),
                ('num_days', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('starting_location', models.CharField(max_length=100)),
                ('accommodation_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Apartment', 'Apartment'), ('Campsite', 'Campsite'), ('Guesthouse', 'Guesthouse')], max_length=50)),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_range', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
